server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_admin?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  email:
    fromEmail: admin@carrental.com
    apiToken: #UMIESCIC TUTAJ TOKEN API MAILTRAP
    inboxId: #UMIESCIC TUTAJ ID SKRZYNKI POCZTOWEJ MAILTRAP
  imgbb:
    apiKey: #UMIESCIC TUTAJ KLUCZ API IMGBB
